language: java
jdk:
  - openjdk8

cache:
  directories:
  - "$HOME/.cache"

services:
  - docker

env:
  global:
    - IMAGE_NAME=thiago1432/api-cartoes

before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t thiago1432/api-cartoes .

before_script:
  - mvn clean install

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
+ - docker tag thiago1432/api-cartoes $DOCKER_USER/thiago1432/api-cartoes:$TRAVIS_BUILD_NUMBER
+ - docker tag thiago1432/api-cartoes $DOCKER_USER/thiago1432/api-cartoes:latest


