apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cartoes-deployment
spec:
  selector:
    matchLabels:
      app: api-cartoes
  template:
    metadata:
      labels:
        app: api-cartoes
    spec:
      containers:
        - name: api-cartoes
          image: thiago1432/api-cartoes:v1.0.2
          ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: api-configmap
          env:
          - name: MONGO_DATABASE
            valueFrom:
              configMapKeyRef:
                name: api-configmap
                key: MONGO_DATABASE
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: api-configmap
                key: MONGO_HOST
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_ROOT_USERNAME
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_ROOT_PASSWORD
                