apiVersion: v1
kind: Service
metadata: 
  name: api-cartoes-service
spec:
  selector: 
    app: api-cartoes
  ports:
    - protocol: TCP
      port: 9595
#      targetPort: 9595
      nodePort: 31777
  type: NodePort