apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
      name: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports: 
          - containerPort: 27017
            name: mongodb
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_ROOT_USERNAME 
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_ROOT_PASSWORD
          volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
      volumes:
       - name: mongo-volume
         hostPath:
           path: /mnt/mongo-volume
           type: DirectoryOrCreate