# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Build Project
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify -Pintegration-test
        
  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: ci
    env:
      REPO: ${{ secrets.DOCKER_REGISTRY }}
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: thiago1432/api-cartoes:main
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_IMAGE }}:main

#       - uses: actions/checkout@v1
#       - name: Docker login
#         run: docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
#       - name: Build
#         run: docker build -t ${{ secrets.DOCKER_REGISTRY_IMAGE }} .
#       - name: Tags
#         run: |
#           docker tag ${{ secrets.DOCKER_REGISTRY_IMAGE }}:main ${{ secrets.DOCKER_REGISTRY_IMAGE }}/${{ secrets.DOCKER_REGISTRY_IMAGE }}:${{ github.sha }}
#           docker tag ${{ secrets.DOCKER_REGISTRY_IMAGE }}:main ${{ secrets.DOCKER_REGISTRY_IMAGE }}/${{ secrets.DOCKER_REGISTRY_IMAGE }}:main
#       - name: Push
#         run: |
#           docker push ${{ secrets.DOCKER_REGISTRY_IMAGE }}/${{ secrets.DOCKER_REGISTRY_IMAGE }}:${{ github.sha }}
#           docker push ${{ secrets.DOCKER_REGISTRY_IMAGE }}/${{ secrets.DOCKER_REGISTRY_IMAGE }}:main
