# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Build Project
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify -Pintegration-test
        
  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: ci
    env:
      REPO: ${{ secrets.DOCKER_REGISTRY }}
    
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ed626639b2c3f20908b915d91957c806
          label: Test Coverage
          message: ${{ env.COVERAGE }}
          color: green
          namedLogo: jest   
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_IMAGE }}:main
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
