# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ci:
    name: Test - Units & Integrations
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Build Project
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify -Pintegration-test
  cd:
    runs-on: ubuntu-latest
    needs: ci
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build
        run: docker build -t back .
      - name: Tags
        run: |
          docker tag back ${{ secrets.DOCKER_HUB_LOGIN }}/back:${{ github.sha }}
          docker tag back ${{ secrets.DOCKER_HUB_LOGIN }}/back:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_HUB_LOGIN }}/back:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_LOGIN }}/back:latest
